// import '../Basics/02-object-interface';
import '../Basics/02_functions/03-functions.js';
// import '../Basics/04-object-destructuring.js';
// import '../Basics/05-function-destructuring.js';
// import '../Basics/06-import-export.js';
// import '../Basics/07-classes.js';
// import '../Basics/08-generics.js';
// import '../Basics/09-decorators.js';
// import '../Basics/10-optional-chaining.js';
// import '../Basics/01_basic_types/02-arrays.js';
// import '../Basics/11-enum.js';
import '../Basics/02_functions/04-exercise.js';
import '../Basics/03_objects/01-objects.js';
import '../Basics/01_basic_types/04-any-unknown-never-void.js';